name: Safe Chain

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version

      - name: Install safe-chain
        run: |
          npm i -g @aikidosec/safe-chain

      - name: Generate package-lock.json (no install)
        run: npm i --package-lock-only

      - name: Setup safe-chain
        run: |
          safe-chain setup-ci

      - name: Install dependencies
        run: npm ci
