name: "Static Analysis"

on:
  push:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version

      - name: Install Dependencies
        run: npm ci

      - name: Run Biome Format Check
        run: npm run format:check

      - name: Run Biome Link Check
        run: npm run lint:check

      - name: Run Build
        run: npm run build
